### ISSUE TITLE
Crashes when beanstalkd is restarted

### ISSUE THREAD

**Issue by wkjagt** [wkjagt/beandispenser#11]
```
Traceback (most recent call last):
  File "/root/.virtualenvs/beandispenser/bin/beandispenser", line 9, in <module>
    load_entry_point('beandispenser==0.1', 'console_scripts', 'beandispenser')()
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beandispenser/beandispenser.py", line 302, in main
  File "/root/.virtualenvs/beandispenser/bin/beandispenser", line 9, in <module>
    load_entry_point('beandispenser==0.1', 'console_scripts', 'beandispenser')()
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beandispenser/beandispenser.py", line 302, in main
    Forker().fork_all()
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beandispenser/beandispenser.py", line 292, in fork_all
        worker.watch()
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beandispenser/beandispenser.py", line 120, in watch
Forker().fork_all()
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beandispenser/beandispenser.py", line 292, in fork_all
        self.info("job {0} done", job.stats()['id'])
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 299, in stats
worker.watch()
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beandispenser/beandispenser.py", line 120, in watch
    self.info("job {0} done", job.stats()['id'])
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 299, in stats
        return self.conn.stats_job(self.jid)
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 252, in stats_job
return self.conn.stats_job(self.jid)
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 252, in stats_job
        ['NOT_FOUND'])
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 118, in _interact_yaml
['NOT_FOUND'])
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 118, in _interact_yaml
        size, = self._interact(command, expected_ok, expected_err)
size, = self._interact(command, expected_ok, expected_err)
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 87, in _interact
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 87, in _interact
        status, results = self._read_response()
  File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 98, in _read_response
status, results = self._read_response()
      File "/root/.virtualenvs/beandispenser/local/lib/python2.7/site-packages/beanstalkc.py", line 98, in _read_response
    raise SocketError()
beanstalkcraise SocketError()
.beanstalkcSocketError
.SocketError
```

**Comment by wkjagt** [comment]
Approach:
1. start beandispenser
2. add long running jobs
3. restart beanstalkd while it's processing a job

**Comment by srj2192** [comment]
Same thing happened with me
